apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocktest-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocktest-backend
  template:
    metadata:
      labels:
        app: mocktest-backend
    spec:
      containers:
        - name: mocktest-backend
          image: harsha3330/mocktest-backend:master-57-date-2024-07-08-dev
          ports:
            - containerPort: 80
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: PORT
          - name: CORS_ORIGIN
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: CORS_ORIGIN
          - name: ACCESS_TOKEN_SECRET
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: ACCESS_TOKEN_SECRET
          - name: ACCESS_TOKEN_EXPIRY
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: ACCESS_TOKEN_EXPIRY
          - name: REFRESH_TOKEN_SECRET
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: REFRESH_TOKEN_SECRET
          - name: REFRESH_TOKEN_EXPIRY
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: REFRESH_TOKEN_EXPIRY
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mocktest-backend-dev
                key: MONGODB_URI
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mocktest-backend-dev
                key: ACCESS_KEY
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mocktest-backend-dev
                key: SECRET_ACCESS_KEY
          - name: CLOUDFRONT_DISTRIBUTION_URL
            valueFrom:
              secretKeyRef:
                name: mocktest-backend-dev
                key: CLOUDFRONT_DISTRIBUTION_URL
          - name: S3_BUCKET_URL
            valueFrom:
              secretKeyRef:
                name: mocktest-backend-dev
                key: S3_BUCKET_URL
          - name: BUCKET_NAME_QUESTIONS
            valueFrom:
              secretKeyRef:
                name: mocktest-backend-dev
                key: BUCKET_NAME_QUESTIONS
          - name: BUCKET_REGION
            valueFrom:
              secretKeyRef:
                name: mocktest-backend-dev
                key: BUCKET_REGION

