apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocktest-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocktest-frontend
  template:
    metadata:
      labels:
        app: mocktest-frontend
    spec:
      containers:
        - name: mocktest-frontend
          image: harsha3330/mocktest-frontend:master-28-date-20240822-114600-dev
          ports:
            - containerPort: 80
